### ISSUE TITLE
Report generation issue

### ISSUE THREAD

**Issue by Samratc030** [netsquare/BrowserBruter#4]
On running an attack on testphp.vulnweb.com the report wasn't successfully generated.
Site:
![3 1](https://github.com/netsquare/BrowserBruter/assets/83419310/2ada7284-a0c0-405a-b59c-83caf345568b)

Command Used:
![3 2](https://github.com/netsquare/BrowserBruter/assets/83419310/4fe11463-35cd-476c-8216-bc60473b7439)

CSV generated:
![3 3](https://github.com/netsquare/BrowserBruter/assets/83419310/720497dd-9b2d-4fc7-9a9e-c15b76ad44d0)

Report not displaying:
![3](https://github.com/netsquare/BrowserBruter/assets/83419310/6181f3e2-f5f7-4b30-92af-afbbc85cebb0)

**Comment by zinja-coder** [comment]
Hey @Samratc030 ,

Thanks for raising the issue. Let us reproduce the issue form our end. We will revert back shortly. 

Thanks & Regards.

**Comment by zinja-coder** [comment]
Hey @Samratc030,

I have looked into the issue and found that there is no button with 'btn-default' and there are no elements 'username', 'password'. 

There are following elements - 'uname', 'pass' and there is following login button - 'submit' as shown below -

![image](https://github.com/netsquare/BrowserBruter/assets/65374935/c424fcbf-3391-415f-b862-297fe6b13619)
 
Following command will do your fuzzing for attack mode - 

` python3 BrowserBruter.py --elements uname,pass --payloads fuzz.txt --attack 1 --target http://testphp.vulnweb.com/login.php --button submit --fill uname,pass`

and it is generating report as expected - 

![image](https://github.com/netsquare/BrowserBruter/assets/65374935/342c361c-3185-4ad3-b575-5aec505a3a95)

For Brute forcing this page following command will work - 

`python3 BrowserBruter.py --elements-payloads uname:usernames.txt,pass:passwords.txt --attack 4 --target http://testphp.vulnweb.com/login.php --button submit` 

Please refer to the official documentation to actually learn how to use the Browser Bruter tool - https://www.net-square.com/browserbruter/UsageManual/

I am closing this one as I am able to both fuzz and generate the report, and issue is caused by incorrect usage of Browser Bruter.

Thanks.
